INSERT INTO USUARIOS (`ID_USUARIO`,`APELLIDO_MATERNO`,`APELLIDO_PATERNO`,`CORREO_ELECTRONICO`,`ESTATUS`,`NOMBRE`,`PASSWORD`,`ROL`)
VALUES (1,'Mendoza','Ramírez','mariagmenr@gmail.com',1,'Mari','12345678',1)
